"""Create tables

Revision ID: 644fbdd6015b
Revises: 
Create Date: 2025-06-25 17:08:50.671731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644fbdd6015b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_model',
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('team_list', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('event_code')
    )
    op.create_table('team_model',
    sa.Column('team_number', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('home_region', sa.String(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('epa_total', sa.Float(), nullable=True),
    sa.Column('auto_epa_total', sa.Float(), nullable=True),
    sa.Column('tele_epa_total', sa.Float(), nullable=True),
    sa.Column('historical_epa', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('historical_auto_epa', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('historical_tele_epa', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('opr', sa.Float(), nullable=True),
    sa.Column('opr_auto', sa.Float(), nullable=True),
    sa.Column('opr_tele', sa.Float(), nullable=True),
    sa.Column('opr_end', sa.Float(), nullable=True),
    sa.Column('historical_opr', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('historical_auto_opr', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('historical_tele_opr', sa.ARRAY(sa.Float()), nullable=True),
    sa.Column('historical_end_opr', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('team_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_model')
    op.drop_table('event_model')
    # ### end Alembic commands ###
