"""Update team model

Revision ID: dd222648da26
Revises: 644fbdd6015b
Create Date: 2025-06-28 14:28:01.227061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd222648da26'
down_revision = '644fbdd6015b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matches', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_model', schema=None) as batch_op:
        batch_op.drop_column('matches')

    # ### end Alembic commands ###
